# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B
model_revision: main
torch_dtype: bfloat16
# use_flash_attention_2: true

# LoRA arguments
use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
lora_modules_to_save:
- score
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- up_proj
- down_proj
- gate_proj

# load_in_4bit: True
# bnb_4bit_quant_type: nf4
# use_bnb_nested_quant: True

# Reward modeling config (1 GPUs assumed)
local_rank: -1
bf16: true
do_eval: true
eval_steps: 100
eval_strategy: steps
gradient_accumulation_steps: 64
gradient_checkpointing: false
deepspeed: null
optim: paged_adamw_32bit
lr_scheduler_type: linear
learning_rate: 2.0e-05
weight_decay: 0.001
log_level: info
logging_steps: 10
logging_strategy: steps
max_length: 1024
max_steps: -1
num_train_epochs: 4
output_dir: logs/Llama-3-8B_sycophancy
resume_from_checkpoint: false
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 1
train_datapath: dataset/sycophancy_dataset/train
eval_datapath: dataset/sycophancy_dataset/train
remove_unused_columns: true
report_to:
- wandb
run_name: "Llama-3-8B_sycophancy" ##
hub_token: null
seed: 42
tf32: true
